### ISSUE TITLE
Discord Theme Bug.

### ISSUE THREAD

**Issue by Jonny0181** [Maxie01/we-made-a-theme#7] opened 2017-02-04 14:32 UTC
Just a small little bug, that should be fixed easily idk tho. 
But it acts like there is a scroll bar on the bottom of Discord.
How to get to this is scroll up and down the chat a little bit, then put your cursor under the box you type in and scroll to the right and left.
You might have to open the member bar a couple of time, and when scrolling down the chat scroll either to the right or left. (Does not work when "New messages" is showing)
Also how I found out how to get this to "un-glitch" is to put my cursor over the members. 
![screenshot_2017-02-04_14-25-50](https://cloud.githubusercontent.com/assets/22266893/22619172/b6577626-eae6-11e6-8f1d-877f54590656.png)

**Comment by SquirrelsMcGee** [comment] 2017-02-04 15:02
Unable to reproduce on windows (both using a mouse with simulated horizontal scroll, and using a trackpad with horizontal scroll), that appears to be some sort of Linux distro, perhaps it is a linux only bug?
Could you disable the theme and try to reproduce the bug?

**Comment by Pierce01** [comment] 2017-02-16 20:06
User has not responded in 12 days, there for this issue is closed and put under `wontfix`

**Comment by robingall2910** [comment] 2017-02-18 16:47
issue isn't closed. @Maxie01

**Closed as completed** 2017-05-26 21:05 UTC
Labels: wontfix
